BiocManager::install('shinyalert')
BiocManager::install('shinyFiles')
BiocManager::install('ggplot2')
BiocManager::install('xlsx')
BiocManager::install('d3heatmap')
BiocManager::install('pixiedust')
BiocManager::install('dplyr')
BiocManager::install('shiny')
BiocManager::install('DT')


library(shinyWidgets)
library(shinyalert)
library(shinyFiles)
library(xlsx)
library(ggplot2)
library(d3heatmap)
library(pixiedust)
library(dplyr)
library(shiny)
library(DT)